### ISSUE TITLE
SVG badges contain truncated versions

### ISSUE THREAD

**Issue by kobalicek** [repology/repology-rs#125]
Thanks for this project & service.

When using the SVG badges link I have noticed that if the versions are not short they are truncated with ellipsis. However, this makes it almost unusable as you cannot see the versions.

I would prefer either an option (like repo.svg?truncate=false or something) or an improved behavior so the matrix contains the information about the versions.

One example could be my own project, which is usually versioned by using a date or a commit hash, which never fits. BTW I'm just a developer of the project, I don't control how it's versioned by package maintainers.

Link:

https://repology.org/badge/vertical-allrepos/asmjit.svg

**Comment by AMDmi3** [comment]
Well it could be a valid issue for a project which had official versioning scheme, but definitely not for this one.

> One example could be my own project, which is usually versioned by using a date or a commit hash, which never fits. BTW I'm just a developer of the project, I don't control how it's versioned by package maintainers.

But you absolutely do, maintainers use upstream versions _when there are ones_. Just start tagging official releases. Preferably [semver](https://semver.org/). That way not only versions will fit on the badge, but can also be compared across distros, and  will convey valuable information about whether there are fixes, new features or api breakage.

**Comment by kobalicek** [comment]
Ok, so if you consider the current SVG ergonomic then the issue can be closed, but I cannot use repology like this.

**Comment by AMDmi3** [comment]
Related: asmjit/asmjit#390

**Comment by kobalicek** [comment]
Yeah I understand. If this project is not a good fit for repology, can I ask for its removal?
