### ISSUE TITLE
`inrepo=<repo>` no longer lists that repo's version of packages

### ISSUE THREAD

**Issue by dg0yt** [repology/repology-rs#48]
E.g. the list of outdated vulnerable ports in vcpkg:
https://repology.org/projects/?search=&maintainer=&category=&inrepo=vcpkg&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on&vulnerable=on

It used to show the vcpkg version of the port, with the corresponding color and vulnerability indicator, until a few days ago. (Good.)

Now it shows only the most recent version available somewhere else. (Bad.)

**Comment by AMDmi3** [comment]
Confirmed, I forgot to reimplement related bits in rust code.

**Comment by dg0yt** [comment]
Great. Thank you very much!
